openapi: 3.0.3
info:
  title: Django Frontend Integrations
  version: 1.0.0
  description: A guide to how to integrate frontend with django.
paths:
  /api/signup/:
    get:
      operationId: signup_retrieve
      tags:
      - signup
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signup'
          description: ''
    post:
      operationId: signup_create
      tags:
      - signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Signup'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Signup'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Signup'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signup'
          description: ''
components:
  schemas:
    Signup:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        passwrod:
          type: string
      required:
      - passwrod
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
