/* tslint:disable */
/* eslint-disable */
/**
 * Django Frontend Integrations
 * A guide to how to integrate frontend with django.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Signup,
} from '../models/index';
import {
    SignupFromJSON,
    SignupToJSON,
} from '../models/index';

export interface SignupCreateRequest {
    signup: Signup;
}

/**
 * 
 */
export class SignupApi extends runtime.BaseAPI {

    /**
     */
    async signupCreateRaw(requestParameters: SignupCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Signup>> {
        if (requestParameters['signup'] == null) {
            throw new runtime.RequiredError(
                'signup',
                'Required parameter "signup" was null or undefined when calling signupCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/signup/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupToJSON(requestParameters['signup']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignupFromJSON(jsonValue));
    }

    /**
     */
    async signupCreate(requestParameters: SignupCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Signup> {
        const response = await this.signupCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async signupRetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Signup>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/signup/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignupFromJSON(jsonValue));
    }

    /**
     */
    async signupRetrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Signup> {
        const response = await this.signupRetrieveRaw(initOverrides);
        return await response.value();
    }

}
