/* tslint:disable */
/* eslint-disable */
/**
 * Django Frontend Integrations
 * A guide to how to integrate frontend with django.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Signup
 */
export interface Signup {
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Signup
     */
    passwrod: string;
}

/**
 * Check if a given object implements the Signup interface.
 */
export function instanceOfSignup(value: object): value is Signup {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('passwrod' in value) || value['passwrod'] === undefined) return false;
    return true;
}

export function SignupFromJSON(json: any): Signup {
    return SignupFromJSONTyped(json, false);
}

export function SignupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Signup {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'passwrod': json['passwrod'],
    };
}

export function SignupToJSON(json: any): Signup {
    return SignupToJSONTyped(json, false);
}

export function SignupToJSONTyped(value?: Signup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'passwrod': value['passwrod'],
    };
}

