/**
 * Django Frontend Integrations
 * A guide to how to integrate frontend with django.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Signup {
    username: string;

    email?: string;

    passwrod: string;

}
